#! /usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

echo "    >>-----> Asking ${WEBAPP_BASE_URL} what about its SOURCE_VERSION"
WEBAPP_SOURCE_VERSION=$(curl ${WEBAPP_BASE_URL}/v1/status | perl -lne 'if ($_ =~ m/sourceVersion": "([^"]*)"/) {print $1}')
export WEBAPP_SOURCE_VERSION
echo "    >>-----> Found that ${WEBAPP_BASE_URL} is running with SOURCE_VERSION=${WEBAPP_SOURCE_VERSION}"

resolve_link() {
  readlink "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

export CI_BASE_DIR="$(abs_dirname "$0")"
${CI_BASE_DIR}/run-remote-tests
